In [11]:
import requests

url = "https://www.nhs.uk/conditions/dementia/living-with-dementia/activities/"

response = requests.get(url, timeout=30)

print(response.status_code)
response.raise_for_status()

200

In [12]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

title = soup.select("main h1")

print(title[0].get_text(strip=True))

Activities for dementia

In [13]:
content = soup.select("main article p, main article li")

print(len(content))

33

In [14]:
for i, item in enumerate(content[:5]):
    print(f"{i + 1}. {item.get_text(' ', strip=True)}")
    print()

1. Having dementia doesn't mean you have to stop doing the things you enjoy.

2. There are all sorts of activities you can do – physical, mental, social and creative – that help you to live well with dementia and improve wellbeing.

3. If you care for someone who has dementia, a shared activity can make both of you happier and able to enjoy quality time together.

4. You can continue with the activities you already enjoy, though they may take longer than they used to, or try new activities.

5. Keeping in touch with people is good for your confidence and mental wellbeing, like meeting up with friends and family.

In [15]:
elements = soup.select(
    "main article h2, main article h3, main article p, main article li"
)

data = []
section = "Introduction"
subsection = ""

for item in elements:
    text = item.get_text(" ", strip=True)

    if item.name == "h2":
        section = text
        subsection = ""

    elif item.name == "h3":
        subsection = text

    else:
        data.append({
            "order": len(data) + 1,
            "section": section,
            "subsection": subsection,
            "tag": item.name,
            "text": text,
            "source_url": url
        })

In [16]:
import pandas as pd

df = pd.DataFrame(data)

print("Number of rows:", len(df))

df.head()

Number of rows: 33

,order,section,subsection,tag,text,source_url
0,1,Introduction,,p,Having dementia doesn't mean you have to stop ...,https://www.nhs.uk/conditions/dementia/living-...
1,2,Introduction,,p,There are all sorts of activities you can do –...,https://www.nhs.uk/conditions/dementia/living-...
2,3,Introduction,,p,"If you care for someone who has dementia, a sh...",https://www.nhs.uk/conditions/dementia/living-...
3,4,Introduction,,p,You can continue with the activities you alrea...,https://www.nhs.uk/conditions/dementia/living-...
4,5,Stay socially active,,p,Keeping in touch with people is good for your ...,https://www.nhs.uk/conditions/dementia/living-...

In [17]:
print(df["tag"].value_counts())

tag
p     18
li    15
Name: count, dtype: int64

In [19]:
print("Empty texts:", (df["text"].str.strip() == "").sum())

Empty texts: 0

In [22]:
print(df.loc[0, "text"])
df.tail()

Having dementia doesn't mean you have to stop doing the things you enjoy.

,order,section,subsection,tag,text,source_url
28,29,Activities for the later stages of dementia,,li,touch,https://www.nhs.uk/conditions/dementia/living-...
29,30,Activities for the later stages of dementia,,li,taste,https://www.nhs.uk/conditions/dementia/living-...
30,31,Activities for the later stages of dementia,,li,smell,https://www.nhs.uk/conditions/dementia/living-...
31,32,Activities for the later stages of dementia,,p,"Playing music, having objects to touch and int...",https://www.nhs.uk/conditions/dementia/living-...
32,33,Activities for the later stages of dementia,,p,Playlist for Life is a music and dementia char...,https://www.nhs.uk/conditions/dementia/living-...

In [25]:
df.to_csv("nhs_activities_dementia.csv", index=False)

from pathlib import Path

print(Path("nhs_activities_dementia.csv").resolve())

/Users/hanrongze/Users/Cssci 2nd year/05 Group Project IV/未命名文件夹/nhs_activities_dementia.csv

In [24]:
saved_df = pd.read_csv("nhs_activities_dementia.csv")

print("Saved rows:", len(saved_df))
saved_df.head()

Saved rows: 33

,order,section,subsection,tag,text,source_url
0,1,Introduction,NaN,p,Having dementia doesn't mean you have to stop ...,https://www.nhs.uk/conditions/dementia/living-...
1,2,Introduction,NaN,p,There are all sorts of activities you can do –...,https://www.nhs.uk/conditions/dementia/living-...
2,3,Introduction,NaN,p,"If you care for someone who has dementia, a sh...",https://www.nhs.uk/conditions/dementia/living-...
3,4,Introduction,NaN,p,You can continue with the activities you alrea...,https://www.nhs.uk/conditions/dementia/living-...
4,5,Stay socially active,NaN,p,Keeping in touch with people is good for your ...,https://www.nhs.uk/conditions/dementia/living-...